export const PRODUCT_LIST_REQUEST: string = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS: string = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL: string = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST: string = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS: string = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL: string = 'PRODUCT_DETAILS_FAIL';